Module-1 Tasks 1-5 completed
js-tasks-ru/jsbasic-20220901_yarmnat7 pull request #2
Opened 2022-09-06 11:25 UTC by NatYarm

Здравствуй, Влад!
У меня небольшой вопрос по структуре кода.
Как лучше писать код внутри функции: нужно ли создавать новые переменные, где будут сохраняться все манипуляции и возвращать уже эту переменную? Например, как в третьем задании  ```{ str[0].toUpperCase() + str.toLowerCase().slice(1);
  return capitalizedStr;}```?
Или же можно сразу возвращать результат без создания переменной ```{return str[0].toUpperCase() + str.toLowerCase().slice(1);}```?

Буду признательна за разъяснения.
Наталья

2022-09-06 11:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-07 12:00 UTC, SinimaWath requested changes

2022-09-07 12:00 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  if (n === 0) return factorial;
если переменная не нужна, ее можно не создавать:
```
if (n === 0) return factorial;

let factorial = 1;

.....
```

2022-09-07 12:00 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
это можно переписать без if:
`return Boolean(name) && !name.includes(" ") && name.length >= 4`

2022-09-07 12:00 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (str === "") return "";
Можно упростить до: `if (!str) return ''`

2022-09-07 12:00 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return capitalizedStr;
Не нужно создавать временную переменую, если можно сразу вернуть значение:
`return str[0].toUpperCase() + str.toLowerCase().slice(1);`

2022-09-07 12:00 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  str.toLowerCase();
Это строчка ничего не делает, `str.toLowerCase()` - не изменяет строку str

2022-09-07 12:00 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  }
это условие излишне:
```
if (str.length <= maxlength) return str;

return str.slice(0, maxlength - 1) +  "…"
```

2022-09-07 17:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-08 14:25 UTC, SinimaWath approved these changes

2022-09-08 14:25 UTC, merged